apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: traceforge-api
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        # Allow multiple containers (sidecar pattern)
        run.googleapis.com/execution-environment: gen2
    spec:
      # Main application container
      containers:
      - name: traceforge-api
        image: gcr.io/gen-lang-client-0516684394/traceforge-api:latest
        ports:
        - containerPort: 8080
        env:
        # Application config
        # Note: PORT is automatically set by Cloud Run
        - name: NODE_ENV
          value: "production"
        
        # OpenTelemetry config (send to local agent)
        - name: TELEMETRY_PROVIDER
          value: "opentelemetry"
        - name: OTEL_SERVICE_NAME
          value: "traceforge-api"
        - name: OTEL_SERVICE_VERSION
          value: "0.1.0"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://localhost:4318"
        - name: OTEL_METRIC_EXPORT_INTERVAL_MS
          value: "5000"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=traceforge-api,service.version=0.1.0,deployment.environment=production"
        
        # API Keys
        - name: GEMINI_API_KEY
          value: "AIzaSyD3-4rMGhAJcJavyVzM_ZWpcwlCXHjyywc"
        - name: DD_API_KEY
          value: "c1a4c227b8252a7da32b23cabf1eef21"
        
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
      
      # Datadog Agent sidecar container
      - name: datadog-agent
        image: gcr.io/datadoghq/agent:latest
        env:
        # Datadog Agent config
        - name: DD_API_KEY
          value: "c1a4c227b8252a7da32b23cabf1eef21"
        - name: DD_SITE
          value: "datadoghq.com"
        - name: DD_HOSTNAME
          value: "traceforge-cloudrun"
        
        # Enable OTLP receiver on port 4318 (HTTP) - matches local test
        - name: DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT
          value: "0.0.0.0:4318"
        
        # Disable features not needed in Cloud Run
        - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
          value: "false"
        - name: DD_APM_ENABLED
          value: "true"
        - name: DD_APM_NON_LOCAL_TRAFFIC
          value: "false"
        - name: DD_LOGS_ENABLED
          value: "false"
        - name: DD_PROCESS_AGENT_ENABLED
          value: "false"
        
        # Cloud Run specific
        - name: ECS_FARGATE
          value: "true"
        
        # Note: Cloud Run doesn't require explicit port declaration for sidecar communication
        # Containers in the same service can communicate via localhost
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
      
      # Service configuration
      containerConcurrency: 80
      timeoutSeconds: 300

  traffic:
  - percent: 100
    latestRevision: true

